"""add_games_tables

Revision ID: f12d308e69f4
Revises: 20260105_activity
Create Date: 2026-01-05 16:29:48.992024

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f12d308e69f4"
down_revision: Union[str, None] = "20260105_activity"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("alert_level", sa.String(length=20), nullable=False),
        sa.Column("alert_message", sa.Text(), nullable=False),
        sa.Column("alert_data", sa.JSON(), nullable=True),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=100), nullable=True),
        sa.Column("parent_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("child_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("is_sent", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_analytics_alerts_parent", "analytics_alerts", ["parent_telegram_id"], unique=False
    )
    op.create_index(
        "idx_analytics_alerts_resolved", "analytics_alerts", ["resolved_at"], unique=False
    )
    op.create_index(
        "idx_analytics_alerts_triggered", "analytics_alerts", ["triggered_at"], unique=False
    )
    op.create_index(
        "idx_analytics_alerts_type_level",
        "analytics_alerts",
        ["alert_type", "alert_level"],
        unique=False,
    )
    op.create_table(
        "analytics_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_key", sa.String(length=100), nullable=False),
        sa.Column("config_value", sa.JSON(), nullable=False),
        sa.Column("config_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_analytics_config_key", "analytics_config", ["config_key"], unique=False)
    op.create_index("uq_analytics_config_key", "analytics_config", ["config_key"], unique=True)
    op.create_table(
        "analytics_trends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("trend_direction", sa.String(length=20), nullable=False),
        sa.Column("trend_strength", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prediction_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_analytics_trends_confidence", "analytics_trends", ["confidence"], unique=False
    )
    op.create_index(
        "idx_analytics_trends_metric", "analytics_trends", ["metric_name"], unique=False
    )
    op.create_index(
        "idx_analytics_trends_period",
        "analytics_trends",
        ["period_start", "period_end"],
        unique=False,
    )
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("game_type", sa.String(length=50), nullable=False),
        sa.Column("game_state", sa.JSON(), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "game_type IN ('tic_tac_toe', 'hangman', '2048')", name="ck_game_sessions_game_type"
        ),
        sa.CheckConstraint(
            "result IS NULL OR result IN ('win', 'loss', 'draw', 'in_progress')",
            name="ck_game_sessions_result",
        ),
        sa.ForeignKeyConstraint(["user_telegram_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_game_sessions_started", "game_sessions", ["started_at"], unique=False)
    op.create_index(
        "idx_game_sessions_user_type",
        "game_sessions",
        ["user_telegram_id", "game_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_sessions_user_telegram_id"),
        "game_sessions",
        ["user_telegram_id"],
        unique=False,
    )
    op.create_table(
        "game_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("game_type", sa.String(length=50), nullable=False),
        sa.Column("total_games", sa.Integer(), server_default="0", nullable=False),
        sa.Column("wins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("losses", sa.Integer(), server_default="0", nullable=False),
        sa.Column("draws", sa.Integer(), server_default="0", nullable=False),
        sa.Column("best_score", sa.Integer(), nullable=True),
        sa.Column("total_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "game_type IN ('tic_tac_toe', 'hangman', '2048')", name="ck_game_stats_game_type"
        ),
        sa.ForeignKeyConstraint(["user_telegram_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_game_stats_updated", "game_stats", ["updated_at"], unique=False)
    op.create_index(
        "idx_game_stats_user_type", "game_stats", ["user_telegram_id", "game_type"], unique=False
    )
    op.create_index(
        op.f("ix_game_stats_user_telegram_id"), "game_stats", ["user_telegram_id"], unique=False
    )
    op.create_index(
        "uq_game_stats_user_type", "game_stats", ["user_telegram_id", "game_type"], unique=True
    )
    op.alter_column(
        "analytics_metrics",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "analytics_metrics",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("idx_analytics_metrics_name"), table_name="analytics_metrics")
    op.drop_index(op.f("idx_analytics_metrics_timestamp"), table_name="analytics_metrics")
    op.drop_index(op.f("idx_analytics_metrics_user"), table_name="analytics_metrics")
    op.drop_index(op.f("idx_analytics_metrics_name_time"), table_name="analytics_metrics")
    op.create_index(
        "idx_analytics_metrics_name_time",
        "analytics_metrics",
        ["metric_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_analytics_metrics_user_time",
        "analytics_metrics",
        ["user_telegram_id", "timestamp"],
        unique=False,
    )
    op.drop_table_comment(
        "analytics_metrics", existing_comment="Метрики для аналитики и мониторинга", schema=None
    )
    op.alter_column(
        "analytics_reports",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "analytics_reports",
        "report_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_analytics_reports_type"), table_name="analytics_reports")
    op.drop_index(op.f("idx_analytics_reports_generated"), table_name="analytics_reports")
    op.create_index(
        "idx_analytics_reports_generated", "analytics_reports", ["generated_at"], unique=False
    )
    op.create_index(
        "idx_analytics_reports_type_period",
        "analytics_reports",
        ["report_type", "report_period"],
        unique=False,
    )
    op.drop_table_comment(
        "analytics_reports", existing_comment="Сгенерированные аналитические отчеты", schema=None
    )
    op.alter_column(
        "chat_history",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "chat_history",
        "message_type",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Тип: user (от пользователя), ai (от AI), system (системное)",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_chat_history_timestamp"), table_name="chat_history")
    op.drop_index(op.f("idx_chat_history_type"), table_name="chat_history")
    op.drop_index(op.f("idx_chat_history_user"), table_name="chat_history")
    op.drop_index(op.f("idx_chat_history_user_time"), table_name="chat_history")
    op.create_index(
        "idx_chat_history_user_time",
        "chat_history",
        ["user_telegram_id", "timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_chat_history_timestamp"), "chat_history", ["timestamp"], unique=False)
    op.create_index(
        op.f("ix_chat_history_user_telegram_id"), "chat_history", ["user_telegram_id"], unique=False
    )
    op.drop_table_comment(
        "chat_history", existing_comment="История сообщений пользователя с AI", schema=None
    )
    op.drop_column("chat_history", "metadata")
    op.drop_column("chat_history", "tokens_used")
    op.alter_column(
        "learning_sessions",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("idx_learning_sessions_completed"), table_name="learning_sessions")
    op.drop_index(op.f("idx_learning_sessions_start"), table_name="learning_sessions")
    op.drop_index(op.f("idx_learning_sessions_subject"), table_name="learning_sessions")
    op.drop_index(op.f("idx_learning_sessions_user"), table_name="learning_sessions")
    op.create_index(
        "idx_sessions_user_date",
        "learning_sessions",
        ["user_telegram_id", "session_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_sessions_user_telegram_id"),
        "learning_sessions",
        ["user_telegram_id"],
        unique=False,
    )
    op.drop_table_comment(
        "learning_sessions", existing_comment="Учебные сессии пользователей", schema=None
    )
    op.drop_column("learning_sessions", "accuracy")
    op.drop_column("learning_sessions", "duration_seconds")
    op.drop_column("learning_sessions", "session_data")
    op.drop_index(op.f("idx_payments_payment_id"), table_name="payments")
    op.drop_index(op.f("idx_payments_status"), table_name="payments")
    op.drop_index(op.f("idx_payments_subscription_id"), table_name="payments")
    op.drop_index(op.f("idx_payments_user_telegram_id"), table_name="payments")
    op.create_index(op.f("ix_payments_payment_id"), "payments", ["payment_id"], unique=True)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(
        op.f("ix_payments_subscription_id"), "payments", ["subscription_id"], unique=False
    )
    op.create_index(
        op.f("ix_payments_user_telegram_id"), "payments", ["user_telegram_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_user_telegram_id"),
        "subscriptions",
        ["user_telegram_id"],
        unique=False,
    )
    op.alter_column(
        "user_events",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "user_events",
        "event_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "user_events",
        "session_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_user_events_timestamp"), table_name="user_events")
    op.drop_index(op.f("idx_user_events_user"), table_name="user_events")
    op.create_index(
        "idx_user_events_user_time", "user_events", ["user_telegram_id", "timestamp"], unique=False
    )
    op.drop_table_comment(
        "user_events", existing_comment="События пользователей для аналитики", schema=None
    )
    op.alter_column(
        "user_progress",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "user_progress",
        "level",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "user_progress",
        "achievements",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        comment=None,
        existing_comment="Массив достижений в формате JSON",
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_index(op.f("idx_user_progress_level"), table_name="user_progress")
    op.drop_index(op.f("idx_user_progress_points"), table_name="user_progress")
    op.drop_index(op.f("idx_user_progress_subject"), table_name="user_progress")
    op.drop_index(op.f("idx_user_progress_user"), table_name="user_progress")
    op.drop_constraint(op.f("uq_user_progress_user_subject"), "user_progress", type_="unique")
    op.create_index(
        "idx_progress_user_subject", "user_progress", ["user_telegram_id", "subject"], unique=False
    )
    op.create_index(
        op.f("ix_user_progress_user_telegram_id"),
        "user_progress",
        ["user_telegram_id"],
        unique=False,
    )
    op.drop_table_comment(
        "user_progress", existing_comment="Прогресс пользователя по предметам", schema=None
    )
    op.drop_column("user_progress", "average_accuracy")
    op.drop_column("user_progress", "total_sessions")
    op.drop_column("user_progress", "total_time_seconds")
    op.alter_column(
        "user_sessions",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "user_sessions",
        "subjects_covered",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "user_sessions",
        "engagement_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Оценка вовлеченности (0-100)",
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "safety_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Оценка безопасности (0-100)",
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "device_info",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("idx_user_sessions_start"), table_name="user_sessions")
    op.drop_index(op.f("idx_user_sessions_user"), table_name="user_sessions")
    op.drop_index(op.f("idx_user_sessions_duration"), table_name="user_sessions")
    op.create_index(
        "idx_user_sessions_duration", "user_sessions", ["session_duration"], unique=False
    )
    op.create_index(
        "idx_user_sessions_user_start",
        "user_sessions",
        ["user_telegram_id", "session_start"],
        unique=False,
    )
    op.drop_table_comment(
        "user_sessions", existing_comment="Сессии пользователей для аналитики", schema=None
    )
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="Уникальный ID из Telegram",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "user_type",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Тип: child (ребенок) или parent (родитель)",
        existing_nullable=False,
        existing_server_default=sa.text("'child'::character varying"),
    )
    op.alter_column(
        "users",
        "parent_telegram_id",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="ID родителя для детского аккаунта",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_users_active"), table_name="users")
    op.drop_index(op.f("idx_users_parent_id"), table_name="users")
    op.drop_index(op.f("idx_users_telegram_id"), table_name="users")
    op.drop_index(op.f("idx_users_type"), table_name="users")
    # Не удаляем constraint, так как он используется внешними ключами
    # op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.drop_table_comment(
        "users", existing_comment="Пользователи системы (дети и родители)", schema=None
    )
    op.drop_column("users", "settings")
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table_comment(
        "users", "Пользователи системы (дети и родители)", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.create_unique_constraint(
        op.f("users_telegram_id_key"), "users", ["telegram_id"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_users_type"), "users", ["user_type"], unique=False)
    op.create_index(op.f("idx_users_telegram_id"), "users", ["telegram_id"], unique=False)
    op.create_index(op.f("idx_users_parent_id"), "users", ["parent_telegram_id"], unique=False)
    op.create_index(op.f("idx_users_active"), "users", ["is_active"], unique=False)
    op.alter_column(
        "users",
        "parent_telegram_id",
        existing_type=sa.BIGINT(),
        comment="ID родителя для детского аккаунта",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "user_type",
        existing_type=sa.VARCHAR(length=20),
        comment="Тип: child (ребенок) или parent (родитель)",
        existing_nullable=False,
        existing_server_default=sa.text("'child'::character varying"),
    )
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.BIGINT(),
        comment="Уникальный ID из Telegram",
        existing_nullable=False,
    )
    op.create_table_comment(
        "user_sessions", "Сессии пользователей для аналитики", existing_comment=None, schema=None
    )
    op.drop_index("idx_user_sessions_user_start", table_name="user_sessions")
    op.drop_index("idx_user_sessions_duration", table_name="user_sessions")
    op.create_index(
        op.f("idx_user_sessions_duration"),
        "user_sessions",
        [sa.literal_column("session_duration DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_user_sessions_user"), "user_sessions", ["user_telegram_id"], unique=False
    )
    op.create_index(
        op.f("idx_user_sessions_start"),
        "user_sessions",
        [sa.literal_column("session_start DESC")],
        unique=False,
    )
    op.alter_column(
        "user_sessions",
        "device_info",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "user_sessions",
        "safety_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Оценка безопасности (0-100)",
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "engagement_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Оценка вовлеченности (0-100)",
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "subjects_covered",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "user_sessions",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.add_column(
        "user_progress",
        sa.Column(
            "total_time_seconds",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user_progress",
        sa.Column(
            "total_sessions",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user_progress",
        sa.Column(
            "average_accuracy",
            sa.NUMERIC(precision=5, scale=2),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table_comment(
        "user_progress", "Прогресс пользователя по предметам", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_user_progress_user_telegram_id"), table_name="user_progress")
    op.drop_index("idx_progress_user_subject", table_name="user_progress")
    op.create_unique_constraint(
        op.f("uq_user_progress_user_subject"),
        "user_progress",
        ["user_telegram_id", "subject"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_user_progress_user"), "user_progress", ["user_telegram_id"], unique=False
    )
    op.create_index(op.f("idx_user_progress_subject"), "user_progress", ["subject"], unique=False)
    op.create_index(
        op.f("idx_user_progress_points"),
        "user_progress",
        [sa.literal_column("points DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_user_progress_level"),
        "user_progress",
        [sa.literal_column("level DESC")],
        unique=False,
    )
    op.alter_column(
        "user_progress",
        "achievements",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        comment="Массив достижений в формате JSON",
        existing_nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "user_progress",
        "level",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "user_progress",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table_comment(
        "user_events", "События пользователей для аналитики", existing_comment=None, schema=None
    )
    op.drop_index("idx_user_events_user_time", table_name="user_events")
    op.create_index(op.f("idx_user_events_user"), "user_events", ["user_telegram_id"], unique=False)
    op.create_index(
        op.f("idx_user_events_timestamp"),
        "user_events",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.alter_column(
        "user_events",
        "session_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_events",
        "event_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "user_events",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_subscriptions_user_telegram_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_payments_user_telegram_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_subscription_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_payment_id"), table_name="payments")
    op.create_index(
        op.f("idx_payments_user_telegram_id"), "payments", ["user_telegram_id"], unique=False
    )
    op.create_index(
        op.f("idx_payments_subscription_id"), "payments", ["subscription_id"], unique=False
    )
    op.create_index(op.f("idx_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("idx_payments_payment_id"), "payments", ["payment_id"], unique=True)
    op.add_column(
        "learning_sessions",
        sa.Column(
            "session_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "learning_sessions",
        sa.Column(
            "duration_seconds",
            sa.INTEGER(),
            sa.Computed(
                "(EXTRACT(epoch FROM (session_end - session_start)))::integer", persisted=True
            ),
            autoincrement=False,
            nullable=True,
            comment="Длительность сессии в секундах (автоматически)",
        ),
    )
    op.add_column(
        "learning_sessions",
        sa.Column(
            "accuracy",
            sa.NUMERIC(precision=5, scale=2),
            sa.Computed(
                "\nCASE\n    WHEN (questions_answered > 0) THEN (((correct_answers)::numeric / (questions_answered)::numeric) * (100)::numeric)\n    ELSE (0)::numeric\nEND",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
            comment="Процент правильных ответов (автоматически вычисляется)",
        ),
    )
    op.create_table_comment(
        "learning_sessions", "Учебные сессии пользователей", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_learning_sessions_user_telegram_id"), table_name="learning_sessions")
    op.drop_index("idx_sessions_user_date", table_name="learning_sessions")
    op.create_index(
        op.f("idx_learning_sessions_user"), "learning_sessions", ["user_telegram_id"], unique=False
    )
    op.create_index(
        op.f("idx_learning_sessions_subject"), "learning_sessions", ["subject"], unique=False
    )
    op.create_index(
        op.f("idx_learning_sessions_start"),
        "learning_sessions",
        [sa.literal_column("session_start DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_learning_sessions_completed"), "learning_sessions", ["is_completed"], unique=False
    )
    op.alter_column(
        "learning_sessions",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.add_column(
        "chat_history",
        sa.Column(
            "tokens_used",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
            comment="Количество токенов использованных AI",
        ),
    )
    op.add_column(
        "chat_history",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table_comment(
        "chat_history", "История сообщений пользователя с AI", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_chat_history_user_telegram_id"), table_name="chat_history")
    op.drop_index(op.f("ix_chat_history_timestamp"), table_name="chat_history")
    op.drop_index("idx_chat_history_user_time", table_name="chat_history")
    op.create_index(
        op.f("idx_chat_history_user_time"),
        "chat_history",
        ["user_telegram_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_chat_history_user"), "chat_history", ["user_telegram_id"], unique=False
    )
    op.create_index(op.f("idx_chat_history_type"), "chat_history", ["message_type"], unique=False)
    op.create_index(
        op.f("idx_chat_history_timestamp"),
        "chat_history",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.alter_column(
        "chat_history",
        "message_type",
        existing_type=sa.VARCHAR(length=50),
        comment="Тип: user (от пользователя), ai (от AI), system (системное)",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_history",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table_comment(
        "analytics_reports",
        "Сгенерированные аналитические отчеты",
        existing_comment=None,
        schema=None,
    )
    op.drop_index("idx_analytics_reports_type_period", table_name="analytics_reports")
    op.drop_index("idx_analytics_reports_generated", table_name="analytics_reports")
    op.create_index(
        op.f("idx_analytics_reports_generated"),
        "analytics_reports",
        [sa.literal_column("generated_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_analytics_reports_type"), "analytics_reports", ["report_type"], unique=False
    )
    op.alter_column(
        "analytics_reports",
        "report_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_reports",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table_comment(
        "analytics_metrics",
        "Метрики для аналитики и мониторинга",
        existing_comment=None,
        schema=None,
    )
    op.drop_index("idx_analytics_metrics_user_time", table_name="analytics_metrics")
    op.drop_index("idx_analytics_metrics_name_time", table_name="analytics_metrics")
    op.create_index(
        op.f("idx_analytics_metrics_name_time"),
        "analytics_metrics",
        ["metric_name", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_analytics_metrics_user"), "analytics_metrics", ["user_telegram_id"], unique=False
    )
    op.create_index(
        op.f("idx_analytics_metrics_timestamp"),
        "analytics_metrics",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_analytics_metrics_name"), "analytics_metrics", ["metric_name"], unique=False
    )
    op.alter_column(
        "analytics_metrics",
        "tags",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "analytics_metrics",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index("uq_game_stats_user_type", table_name="game_stats")
    op.drop_index(op.f("ix_game_stats_user_telegram_id"), table_name="game_stats")
    op.drop_index("idx_game_stats_user_type", table_name="game_stats")
    op.drop_index("idx_game_stats_updated", table_name="game_stats")
    op.drop_table("game_stats")
    op.drop_index(op.f("ix_game_sessions_user_telegram_id"), table_name="game_sessions")
    op.drop_index("idx_game_sessions_user_type", table_name="game_sessions")
    op.drop_index("idx_game_sessions_started", table_name="game_sessions")
    op.drop_table("game_sessions")
    op.drop_index("idx_analytics_trends_period", table_name="analytics_trends")
    op.drop_index("idx_analytics_trends_metric", table_name="analytics_trends")
    op.drop_index("idx_analytics_trends_confidence", table_name="analytics_trends")
    op.drop_table("analytics_trends")
    op.drop_index("uq_analytics_config_key", table_name="analytics_config")
    op.drop_index("idx_analytics_config_key", table_name="analytics_config")
    op.drop_table("analytics_config")
    op.drop_index("idx_analytics_alerts_type_level", table_name="analytics_alerts")
    op.drop_index("idx_analytics_alerts_triggered", table_name="analytics_alerts")
    op.drop_index("idx_analytics_alerts_resolved", table_name="analytics_alerts")
    op.drop_index("idx_analytics_alerts_parent", table_name="analytics_alerts")
    op.drop_table("analytics_alerts")
    # ### end Alembic commands ###
